import { useCallback, useEffect, useState } from "react";
import type { Generation, Listing3DAsset, Listing3DTag, ListingDetail, ListingSummary, TagCategory, Vec3 } from "./data/types.ts";
import { TAG_CATEGORIES } from "./data/types.ts";
import { fixtureApi } from "./data/fixtures.ts";
import { desktop } from "./data/garageApi.ts";
import { CATEGORY_VIEWS, VIEW_LABELS } from "./data/photos.ts";
import { AZIMUTH_BY_LABEL, EXTERIOR_LABELS } from "./data/novel.ts";
import { addTag, deleteTag, updateTag } from "./data/tags.ts";
import Viewer, { validateAssetUrl, viewFor, type Pose, type ViewBucket } from "./viewer/Viewer.tsx";
import Dashboard, { pipelineLabel, STAGE_LABEL, type RecentListing } from "./ui/Dashboard.tsx";
import Img from "./ui/Img.tsx";
import SpinViewer from "./viewer/SpinViewer.tsx";

type Feature = "dashboard" | "3d" | "settings";

// Desktop shell = live Garage data via the main process; plain browser = offline fixtures.
const api = desktop ?? fixtureApi;

type Tab = "360" | "photos" | "versions";

const STATUS_LABEL = { none: "No 360", queued: "Queued", processing: "Processing", ready: "Ready", failed: "Failed" } as const;

// Per-viewer convenience only (plan: never state that must persist); storage can be blocked, so every access is guarded.
const RECENT_KEY = "gi.recent";
function readRecent(): RecentListing[] {
  try { return JSON.parse(localStorage.getItem(RECENT_KEY) ?? "[]"); } catch { return []; }
}
function pushRecent(r: RecentListing) {
  const next = [r, ...readRecent().filter((x) => x.id !== r.id)].slice(0, 8);
  try { localStorage.setItem(RECENT_KEY, JSON.stringify(next)); } catch { /* storage unavailable */ }
  return next;
}

const DISCLAIMER: Record<string, string> = {
  "photo-spin": "Real listing photos at the angles they were taken; the angles in between are AI-generated.",
  "novel-view-splat": "Some angles were generated by AI from the listing photos. Use the real photos as evidence.",
  "posed-test": "Pipeline test: rendered from an earlier model, not reconstructed from this listing's photos.",
};

export default function App() {
  const [feature, setFeature] = useState<Feature>(desktop ? "dashboard" : "3d");
  const [query, setQuery] = useState("");
  const [results, setResults] = useState<ListingSummary[]>([]);
  const [listing, setListing] = useState<ListingDetail | null>(null);
  const [asset, setAsset] = useState<Listing3DAsset | null>(null);
  const [versions, setVersions] = useState<Listing3DAsset[]>([]);
  const [tab, setTab] = useState<Tab>("360");
  const [assetError, setAssetError] = useState<string | null>(null);
  const [tags, setTags] = useState<Listing3DTag[]>([]);
  const [selectedTagId, setSelectedTagId] = useState<string | null>(null);
  const [editing, setEditing] = useState(false);
  const [placing, setPlacing] = useState(false);
  const [pose, setPose] = useState<Pose | null>(null);
  const [capturePose, setCapturePose] = useState<(() => Pose) | null>(null);
  const [status, setStatus] = useState<{ garage: boolean; sync?: boolean }>({ garage: false });
  const [genError, setGenError] = useState<string | null>(null);
  const [generations, setGenerations] = useState<Generation[]>([]);
  const [pending, setPending] = useState<Listing3DAsset[]>([]);
  const [recent, setRecent] = useState<RecentListing[]>(readRecent);
  const [pickedVersion, setPickedVersion] = useState<string | null>(null);
  const [viewBucket, setViewBucket] = useState<ViewBucket>("front_34");
  const [photoIdx, setPhotoIdx] = useState(0);
  const [spinGoto, setSpinGoto] = useState<{ azimuth: number; n: number } | null>(null);

  useEffect(() => void desktop?.status().then(setStatus), []);
  // Automation hook for the smoke/recording harness (electron/smoke.ts): jump the camera to an exact pose.
  useEffect(() => {
    (window as unknown as { __giSetPose?: (p: Pose) => void }).__giSetPose = (p) => setPose({ ...p });
  }, []);

  // Generation status lives in the main process (persisted); the dashboard just reads it.
  useEffect(() => {
    if (!desktop) return;
    const load = async () => {
      setGenerations(await desktop!.listGenerations());
      setPending(await desktop!.listPending());
    };
    void load();
    const t = setInterval(load, 3000);
    return () => clearInterval(t);
  }, []);

  useEffect(() => void api.searchListings(query).then(setResults), [query]);

  const openListing = async (id: string, assetId?: string) => {
    setFeature("3d");
    const [l, current, vs] = await Promise.all([api.getListing(id), api.getCurrentAsset(id), api.listAssets(id)]);
    const a = (assetId && vs.find((v) => v.id === assetId)) || current;
    setListing(l);
    setAsset(a);
    setVersions(vs);
    setPickedVersion(assetId ?? null);
    setTab("360");
    setSelectedTagId(null);
    setEditing(false);
    setPlacing(false);
    setPose(viewFor(a).presets.Reset);
    setTags(a ? await api.listTags(a.id) : []);
    setAssetError(a?.format === "glb" && a.storageKey ? await validateAssetUrl(a.storageKey) : null);
    setRecent(pushRecent({ id: l.id, title: l.listingTitle, secondaryId: l.secondaryId }));
  };

  // When this listing's generation finishes, show the new version without a manual refresh.
  const listingGen = listing ? generations.find((g) => g.listingId === listing.id) : undefined;
  useEffect(() => {
    if (listing && listingGen?.stage === "ready" && listingGen.assetId && !versions.some((v) => v.id === listingGen.assetId)) {
      void api.listAssets(listing.id).then(setVersions);
    }
  }, [listingGen?.stage, listingGen?.assetId, listing, versions]);

  const commitTags = (next: Listing3DTag[]) => {
    setTags(next);
    if (asset) void api.saveTags(asset.id, next);
  };

  const selectTag = (id: string | null) => {
    setSelectedTagId(id);
    const t = tags.find((x) => x.id === id);
    if (t) setPose(t.camera ?? { position: [t.position[0] + 4, t.position[1] + 2, t.position[2] + 4], target: t.position });
  };

  const generate = async () => {
    if (!listing || !desktop) return;
    setGenError(null);
    try {
      await desktop.startGeneration(listing.id);
      setGenerations(await desktop.listGenerations());
    } catch (e) {
      setGenError((e as Error).message);
    }
  };

  const review = async (s: "approved" | "rejected", target: Listing3DAsset | null = asset) => {
    if (!target || !desktop) return;
    await desktop.reviewAsset(target.id, s);
    setVersions(await api.listAssets(target.listingId));
    if (asset?.id === target.id) setAsset({ ...target, reviewStatus: s });
  };

  // Viewing a specific version from the Versions tab; tags follow the version.
  const viewVersion = async (v: Listing3DAsset) => {
    setPickedVersion(v.id);
    setAsset(v);
    setPose(viewFor(v).presets.Reset);
    setTags(await api.listTags(v.id));
    setSelectedTagId(null);
    setTab("360");
    setAssetError(v.format === "glb" && v.storageKey ? await validateAssetUrl(v.storageKey) : null);
  };

  const exteriorCount = listing ? EXTERIOR_LABELS.filter((l) => listing.photos.some((p) => p.viewLabel === l)).length : 0;
  const genActive = listingGen && listingGen.stage !== "ready" && listingGen.stage !== "failed";

  const onCapturePose = useCallback((fn: () => Pose) => setCapturePose(() => fn), []);
  const selected = tags.find((t) => t.id === selectedTagId) ?? null;
  // Real photos taken from roughly the direction the camera is looking; the 360 orbits, the photo tells the truth.
  // Lead with the photo this version was built from (a full exterior shot), not the first close-up in the gallery.
  const anglePhotos = listing
    ? listing.photos.filter((p) => p.viewLabel === viewBucket).sort((a, b) => Number(asset?.sourceImageIds.includes(b.id) ?? 0) - Number(asset?.sourceImageIds.includes(a.id) ?? 0))
    : [];
  const anglePhoto = anglePhotos[photoIdx % Math.max(anglePhotos.length, 1)];
  const viewable = asset && asset.processingStatus === "ready" && (asset.reviewStatus === "approved" || editing || pickedVersion === asset.id);
  const titles = Object.fromEntries([...results.map((r) => [r.id, r.listingTitle]), ...generations.map((g) => [g.listingId, g.title]), ...recent.map((r) => [r.id, r.title])]);

  return (
    <div className="shell">
      <nav className="sidebar">
        <div className="brand">
          <span className="brand-mark">G</span>
          <div>
            <div className="brand-name">Garage Intelligence</div>
            <div className="brand-sub">Internal tools</div>
          </div>
        </div>
        {desktop && <button className={feature === "dashboard" ? "active" : ""} onClick={() => setFeature("dashboard")}>Dashboard{generations.some((g) => g.stage !== "ready" && g.stage !== "failed") ? " ●" : ""}</button>}
        <button className={feature === "3d" ? "active" : ""} onClick={() => setFeature("3d")}>3D Listings</button>
        <button className={feature === "settings" ? "active" : ""} onClick={() => setFeature("settings")}>Settings</button>
      </nav>

      {feature === "dashboard" ? (
        <Dashboard generations={generations} pending={pending} titles={titles} recent={recent} onOpen={openListing}
          onRetry={async (id) => { await desktop?.retryGeneration(id); setGenerations((await desktop?.listGenerations()) ?? []); }} />
      ) : feature === "settings" ? (
        <main className="settings">
          <h2>Settings</h2>
          <p>Garage listings: <b>{desktop ? (status.garage ? "connected (read-only)" : "GARAGE_DATABASE_URL not set") : "offline fixtures (browser mode)"}</b></p>
          <p>360 generation: <b>novel-view splat</b> (Stable Virtual Camera views on Modal, then Splatfacto). Needs the uv CLI and a Modal login on this machine.</p>
          <p>Desktop bridge: {desktop?.platform ?? "browser (no Electron)"}</p>
        </main>
      ) : (
        <>
          <aside className="browser">
            <input placeholder="Search title or listing #" value={query} onChange={(e) => setQuery(e.target.value)} />
            <ul>
              {results.map((r) => (
                <li key={r.id} className={listing?.id === r.id ? "active" : ""} onClick={() => openListing(r.id)}>
                  {r.thumbnailUrl ? <Img src={r.thumbnailUrl} width={160} alt="" /> : <div className="thumb-empty" />}
                  <div>
                    <div className="title">{r.listingTitle}</div>
                    <div className="meta">#{r.secondaryId} · <span className={`pill ${r.processingStatus}`}>{STATUS_LABEL[r.processingStatus]}</span></div>
                  </div>
                </li>
              ))}
              {results.length === 0 && <li className="empty">No listings match.</li>}
            </ul>
          </aside>

          <main className="viewer">
            {!listing ? (
              <div className="viewport-state center">Select a listing to open its 3D representation.</div>
            ) : (
              <>
                <header>
                  <div>
                    <div className="title">{listing.listingTitle} <span className="meta">#{listing.secondaryId}</span></div>
                    <div className="meta">
                      {asset ? <><span className={`pill ${asset.format === "glb" ? "legacy" : asset.pipelineVersion}`}>{pipelineLabel(asset.pipelineVersion)}</span> · v{asset.version} · {STATUS_LABEL[asset.processingStatus]} · review {asset.reviewStatus}</> : "No 360 view yet"}
                      {genActive && <> · <span className="pill queued">{STAGE_LABEL[listingGen!.stage]}{listingGen!.total != null && listingGen!.current != null ? ` ${listingGen!.current.toLocaleString()}/${listingGen!.total.toLocaleString()}` : ""}</span></>}
                    </div>
                  </div>
                  <div className="actions">
                    {asset?.processingStatus === "ready" && <button onClick={() => { setEditing((e) => !e); setPlacing(false); }}>{editing ? "Done editing" : "Edit tags"}</button>}
                    {editing && asset && asset.reviewStatus !== "approved" && <button className="primary" onClick={() => review("approved")}>Approve</button>}
                    {editing && asset && asset.reviewStatus !== "rejected" && <button onClick={() => review("rejected")}>Reject</button>}
                    {desktop && (
                      <button onClick={generate} disabled={exteriorCount < 3 || !!genActive}
                        title={exteriorCount < 3 ? "Needs at least 3 labelled exterior photos (front, 3/4, side, rear)" : genActive ? "A generation is already running" : `Uses ${exteriorCount} exterior photos; the other angles are generated`}>
                        {genActive ? "Generating…" : "Generate 360"}
                      </button>
                    )}
                  </div>
                </header>

                <div className="tabs">
                  <button className={tab === "360" ? "active" : ""} onClick={() => setTab("360")}>360 View</button>
                  <button className={tab === "photos" ? "active" : ""} onClick={() => setTab("photos")}>Photos ({listing.photos.length})</button>
                  <button className={tab === "versions" ? "active" : ""} onClick={() => setTab("versions")}>Versions{versions.length ? ` (${versions.length})` : ""}</button>
                </div>
                {tab === "photos" ? (
                  <PhotosTab listing={listing} />
                ) : tab === "versions" ? (
                  <div className="versions">
                    {versions.length === 0 && <p className="meta">No generated versions yet.</p>}
                    {versions.map((v) => (
                      <div key={v.id} className={`version ${asset?.id === v.id ? "active" : ""}`}>
                        <div>
                          <div className="title">v{v.version} <span className={`pill ${v.format === "glb" ? "legacy" : v.pipelineVersion}`}>{pipelineLabel(v.pipelineVersion)}</span> <span className={`pill ${v.processingStatus}`}>{STATUS_LABEL[v.processingStatus]}</span> <span className={`pill ${v.reviewStatus}`}>{v.reviewStatus}</span></div>
                          <div className="meta">{v.pipelineVersion} · {v.format} · {v.sourceImageIds.length ? `${v.sourceImageIds.length} source photos · ` : ""}{new Date(v.createdAt).toLocaleString()}{v.error ? ` · ${v.error}` : ""}</div>
                        </div>
                        <div className="row">
                          <button onClick={() => viewVersion(v)} disabled={v.processingStatus !== "ready"}>{asset?.id === v.id ? "Viewing" : "View"}</button>
                          {api === desktop && v.reviewStatus !== "approved" && v.processingStatus === "ready" && <button className="primary" onClick={() => review("approved", v)}>Approve</button>}
                          {api === desktop && v.reviewStatus !== "rejected" && <button onClick={() => review("rejected", v)}>Reject</button>}
                        </div>
                      </div>
                    ))}
                  </div>
                ) : (
                <div className="viewport">
                  {viewable && asset && !assetError ? (
                    asset.format === "spin" ? (
                      <SpinViewer asset={asset} tags={tags} selectedTagId={selectedTagId} onSelectTag={setSelectedTagId} goto={spinGoto}
                        onViewChange={(b) => { setViewBucket(b); setPhotoIdx(0); }} />
                    ) :
                    <Viewer asset={asset} tags={tags} selectedTagId={selectedTagId} onSelectTag={selectTag} placing={placing}
                      onPlace={(p: Vec3) => { const next = addTag(tags, asset.id, p); commitTags(next); setSelectedTagId(next[next.length - 1].id); setPlacing(false); }}
                      pose={pose} onCapturePose={onCapturePose} onViewChange={(b) => { setViewBucket(b); setPhotoIdx(0); }} />
                  ) : (
                    <div className="viewport-state center">
                      {genError ? `Generation request failed: ${genError}` : assetError ?? (
                        genActive ? `${STAGE_LABEL[listingGen!.stage]}… see the Dashboard for progress.` :
                        !asset ? `No 360 view yet. ${exteriorCount >= 3 ? `Generate one from ${exteriorCount} labelled exterior photos.` : "This listing needs at least 3 labelled exterior photos."}` :
                        asset.processingStatus === "failed" ? `Generation failed: ${asset.error ?? "unknown error"}` :
                        asset.processingStatus === "ready" ? (asset.reviewStatus === "rejected" ? "This version was rejected. Generate a new one or pick another in Versions." : "Version awaiting review. Open it from Versions or click Edit tags to inspect and approve it.") :
                        `Generation ${STATUS_LABEL[asset.processingStatus].toLowerCase()}… this usually takes a few minutes.`
                      )}
                    </div>
                  )}
                  {viewable && !assetError && (
                    <div className="hud">
                      {asset.format === "spin"
                        ? Object.entries({ Reset: 45, Front: 0, Rear: 180, Left: 90, Right: 270 }).map(([k, az]) => <button key={k} onClick={() => setSpinGoto((g) => ({ azimuth: az, n: (g?.n ?? 0) + 1 }))}>{k}</button>)
                        : Object.entries(viewFor(asset).presets).map(([k, p]) => <button key={k} onClick={() => setPose({ ...p })}>{k}</button>)}
                      {editing && asset.format !== "spin" && <button className={placing ? "primary" : ""} onClick={() => setPlacing((p) => !p)}>{placing ? "Click the model…" : "+ Add tag"}</button>}
                    </div>
                  )}
                  {viewable && !assetError && asset.format !== "spin" /* in a spin the frame is already the photo */ && (
                    <div className="angle-photo">
                      {anglePhoto ? (
                        <>
                          <Img src={anglePhoto.url} width={640} alt="" onClick={() => setPhotoIdx((i) => i + 1)} title="Click for the next photo from this angle" />
                          <div className="meta">Real photo · {VIEW_LABELS[viewBucket]}{anglePhotos.length > 1 ? ` · ${(photoIdx % anglePhotos.length) + 1}/${anglePhotos.length}` : ""}</div>
                        </>
                      ) : (
                        <div className="meta">No listing photo from this angle ({VIEW_LABELS[viewBucket]})</div>
                      )}
                    </div>
                  )}
                  {asset && viewable && DISCLAIMER[asset.pipelineVersion] && <div className="disclaimer">{DISCLAIMER[asset.pipelineVersion]}</div>}
                </div>
                )}
              </>
            )}
          </main>

          <aside className="panel">
            {!listing ? null : editing && selected && asset ? (
              <TagEditor tag={selected} listing={listing} capturePose={capturePose}
                onChange={(patch) => commitTags(updateTag(tags, selected.id, patch))}
                onDelete={() => { commitTags(deleteTag(tags, selected.id)); setSelectedTagId(null); }} />
            ) : (
              <Inspection listing={listing} tags={tags} selected={selected} onSelect={selectTag} />
            )}
          </aside>
        </>
      )}
    </div>
  );
}

// Exterior photos in order around the vehicle (front -> rear, plan §7), then everything else grouped by label.
function PhotosTab({ listing }: { listing: ListingDetail }) {
  const exterior = listing.photos.filter((p) => p.viewLabel && p.viewLabel in AZIMUTH_BY_LABEL).sort((a, b) => AZIMUTH_BY_LABEL[a.viewLabel!] - AZIMUTH_BY_LABEL[b.viewLabel!]);
  const groups = new Map<string, typeof listing.photos>();
  for (const p of listing.photos) if (!exterior.includes(p)) groups.set(p.viewLabel ?? "unlabelled", [...(groups.get(p.viewLabel ?? "unlabelled") ?? []), p]);
  const grid = (ps: typeof listing.photos) => (
    <div className="photos wide">{ps.map((p) => <figure key={p.id}><Img src={p.url} width={480} alt="" /><figcaption>{p.viewLabel ? VIEW_LABELS[p.viewLabel] ?? p.viewLabel : "Photo"}{p.viewLabel && p.viewLabel in AZIMUTH_BY_LABEL ? ` · ${AZIMUTH_BY_LABEL[p.viewLabel]}°` : ""}</figcaption></figure>)}</div>
  );
  return (
    <div className="photos-tab">
      <h4>Exterior, around the vehicle</h4>
      {exterior.length ? grid(exterior) : <p className="meta">No labelled exterior photos.</p>}
      {[...groups].map(([label, ps]) => <section key={label}><h4>{VIEW_LABELS[label] ?? label} ({ps.length})</h4>{grid(ps)}</section>)}
    </div>
  );
}

function Inspection({ listing, tags, selected, onSelect }: { listing: ListingDetail; tags: Listing3DTag[]; selected: Listing3DTag | null; onSelect: (id: string) => void }) {
  const photos = selected ? listing.photos.filter((p) => selected.evidence.imageIds.includes(p.id)) : listing.photos;
  const fields = selected ? selected.evidence.fields : Object.keys(listing.attributes);
  return (
    <>
      <h3>{selected ? selected.label : "Listing"}</h3>
      {selected?.description && <p className="meta">{selected.description}</p>}
      {!selected && listing.listingDescription && <p className="meta">{listing.listingDescription}</p>}
      <section>
        <h4>Photos {selected && <span className="meta">from listing</span>}</h4>
        {photos.length === 0 ? <p className="meta">No photos linked.</p> : (
          <div className="photos">{photos.map((p) => <figure key={p.id}><Img src={p.url} width={480} alt={p.viewLabel ?? ""} /><figcaption>{p.viewLabel ? VIEW_LABELS[p.viewLabel] ?? p.viewLabel : "Photo"}</figcaption></figure>)}</div>
        )}
      </section>
      <section>
        <h4>Specifications</h4>
        {fields.length === 0 ? <p className="meta">No specifications linked.</p> : (
          <dl>{fields.map((f) => <div key={f}><dt>{f}</dt><dd className={listing.attributes[f] ? "" : "meta"}>{listing.attributes[f] ?? "Unavailable"}</dd></div>)}</dl>
        )}
      </section>
      <section>
        <h4>Parts</h4>
        {tags.length === 0 ? <p className="meta">No tags on this asset version.</p> : (
          <ul className="parts">{tags.map((t) => <li key={t.id}><button className={t.id === selected?.id ? "active" : ""} onClick={() => onSelect(t.id)}>{t.label} <span className="meta">{t.category}</span></button></li>)}</ul>
        )}
      </section>
    </>
  );
}

function TagEditor({ tag, listing, capturePose, onChange, onDelete }: { tag: Listing3DTag; listing: ListingDetail; capturePose: (() => Pose) | null; onChange: (patch: Partial<Listing3DTag>) => void; onDelete: () => void }) {
  const toggle = (list: string[], v: string) => (list.includes(v) ? list.filter((x) => x !== v) : [...list, v]);
  return (
    <>
      <h3>Edit tag</h3>
      <label>Label<input value={tag.label} onChange={(e) => onChange({ label: e.target.value })} /></label>
      <label>Category
        <select value={tag.category} onChange={(e) => { const category = e.target.value as TagCategory; const views = CATEGORY_VIEWS[category]; const imageIds = listing.photos.filter((p) => p.viewLabel && views.includes(p.viewLabel)).map((p) => p.id); onChange({ category, label: tag.label.startsWith("New ") ? category : tag.label, evidence: { ...tag.evidence, imageIds: imageIds.length ? imageIds : tag.evidence.imageIds } }); }}>{TAG_CATEGORIES.map((c) => <option key={c}>{c}</option>)}</select>
      </label>
      <label>Description<textarea rows={3} value={tag.description ?? ""} onChange={(e) => onChange({ description: e.target.value || undefined })} /></label>
      <section>
        <h4>Photos</h4>
        {listing.photos.map((p) => <label key={p.id} className="check"><input type="checkbox" checked={tag.evidence.imageIds.includes(p.id)} onChange={() => onChange({ evidence: { ...tag.evidence, imageIds: toggle(tag.evidence.imageIds, p.id) } })} /><Img src={p.url} width={120} alt="" className="mini" />{p.viewLabel ? VIEW_LABELS[p.viewLabel] ?? p.viewLabel : "Photo"}</label>)}
      </section>
      <section>
        <h4>Listing fields</h4>
        {Object.keys(listing.attributes).length === 0 && <p className="meta">This listing has no attributes.</p>}
        {Object.keys(listing.attributes).map((f) => <label key={f} className="check"><input type="checkbox" checked={tag.evidence.fields.includes(f)} onChange={() => onChange({ evidence: { ...tag.evidence, fields: toggle(tag.evidence.fields, f) } })} />{f}</label>)}
      </section>
      <section>
        <h4>Camera</h4>
        <p className="meta">{tag.camera ? "Saved view set." : "No saved view; focus falls back to the tag position."}</p>
        <div className="row">
          <button onClick={() => capturePose && onChange({ camera: capturePose() })} disabled={!capturePose}>Save current view</button>
          {tag.camera && <button onClick={() => onChange({ camera: undefined })}>Clear</button>}
        </div>
      </section>
      <p className="meta">Position (model-local): {tag.position.join(", ")} · asset {tag.assetVersionId}</p>
      <button className="danger" onClick={onDelete}>Delete tag</button>
    </>
  );
}
